@startuml Medication Reminder App
left to right direction

actor "User" as user

user -- (Add Medication)
user -- (Manage Medication Info)
user -- (View Medications)

(Add Medication) <.. (Enter Medication Details) : <<include>>

(Manage Medication Info) <.. (Edit Medication) : <<include>>
(Manage Medication Info) <.. (Delete Medication) : <<include>>

(View Medications) <.. (Retrieve Medication List) : <<include>>

user -- (Log Dose)
user -- (View Medication History)
user -- (Receive Reminder Notifications)

(Log Dose) <.. (Mark as Taken) : <<include>>
(Log Dose) <.. (Snooze Reminder) : <<include>>
(Log Dose) <.. (Skip Dose) : <<include>>

(View Medication History) <.. (View Doses Log) : <<include>>
(View Medication History) <.. (View Adherence Statistics) : <<include>>

(Receive Reminder Notifications) <.. (Receive Notification) : <<include>>

user -- (User Authentication)

(User Authentication) <.. (Login) : <<include>>
(User Authentication) <.. (Logout) : <<include>>

@enduml
