@startuml sprint 1
left to right direction

actor "User" as user

user -- (Add Medication)
user -- (Manage Medication Info)
user -- (View Medications)

(Add Medication) <.. (Enter Medication Details) : <<include>>
(Add Medication) <.. (Verify Drug Information) : <<include>>

(Manage Medication Info) <.. (Edit Medication) : <<include>>
(Manage Medication Info) <.. (Delete Medication) : <<include>>

(View Medications) <.. (Retrieve Medication List) : <<include>>

@enduml
